# Generated by Django 4.2 on 2024-09-14 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Komment text:')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Komment shiqqan waqti')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.pc')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Komment',
                'verbose_name_plural': 'Kommentlar',
            },
        ),
    ]
