# Generated by Django 4.2 on 2024-09-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='movie',
            new_name='tovar',
        ),
    ]
